// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
<<<<<<< HEAD
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
=======
>>>>>>> fac1221b81 ("hardhat": patch)

import { A$Type } from "./A";
import { B$Type } from "./B";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["A"]: A$Type;
    ["B"]: B$Type;
    ["contracts/A.sol:A"]: A$Type;
    ["contracts/A.sol:B"]: B$Type;
  }
<<<<<<< HEAD

  interface ContractTypesMap {
    ["A"]: GetContractReturnType<A$Type["abi"]>;
    ["B"]: GetContractReturnType<B$Type["abi"]>;
    ["contracts/A.sol:A"]: GetContractReturnType<A$Type["abi"]>;
    ["contracts/A.sol:B"]: GetContractReturnType<B$Type["abi"]>;
  }
=======
>>>>>>> fac1221b81 ("hardhat": patch)
}
