// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    B: never;
  }
<<<<<<< HEAD

  interface ContractTypesMap {
    B: never;
  }
=======
>>>>>>> fac1221b81 ("hardhat": patch)
}
