name: hardhat-foundry CI
on:
  push:
    branches: [$default-branch]
    paths:
      - "packages/hardhat-foundry/**"
      - "packages/hardhat-common/**"
      - "config/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "packages/hardhat-foundry/**"
      - "packages/hardhat-common/**"
      - "config/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/hardhat-foundry

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_on_windows:
    name: Test hardhat-foundry on Windows with Node 22
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        env:
          FORCE_COLOR: 3
        run: pnpm test

  test_on_macos:
    name: Test hardhat-foundry on MacOS with Node 22
    runs-on: macos-latest
    # disable until actions/virtual-environments#4896 is fixed
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        env:
          FORCE_COLOR: 3
        run: pnpm test

  test_on_linux:
    name: Test hardhat-foundry on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        env:
          FORCE_COLOR: 3
        run: pnpm test
