# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# Puppet Lint tests Puppet code against the recommended Puppet language style guide.
# https://puppet.com/docs/puppet/7/style_guide.html
# Puppet Lint validates only code style; it does not validate syntax.
# To test syntax, use Puppet's puppet parser validate command.
# More details at https://github.com/puppetlabs/puppet-lint/

name: puppet-lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  puppet-lint:
    runs-on: ubuntu-24.04-x64

    steps:
      - name: Set up Ruby
        run: |
          # Install rbenv
          curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-installer | bash
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(rbenv init -)"
          
          # Install Ruby using rbenv
          rbenv install 2.7.0
          rbenv global 2.7.0
          # Verify installation
          ruby --version
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run puppet-lint
        run: bundle exec puppet-lint ./
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install puppet-lint
        run: gem install puppet-lint

      - name: Run puppet-lint
        run: puppet-lint . --sarif > puppet-lint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: puppet-lint-results.sarif
          wait-for-processing: true
          
# Updated steps in .github/workflows/puppet-lint.yml
      - name: Checkout code
        uses: actions/checkout@v4

  # Install Ruby manually using ruby-build
      - name: Install ruby-build
        run: |
         sudo apt-get update
         sudo apt-get install -y build-essential libssl-dev zlib1g-dev
         git clone https://github.com/rbenv/ruby-build.git ~/.ruby-build
         sudo ~/.ruby-build/install.sh
      - name: Install Ruby 2.7
        run: |
          ruby-build 2.7.0 $RUNNER_TOOL_CACHE/ruby/2.7.0
          echo "Ruby installed to $RUNNER_TOOL_CACHE/ruby/2.7.0"
  # Add Ruby to PATH
      - name: Configure Ruby PATH
        run: echo "$RUNNER_TOOL_CACHE/ruby/2.7.0/bin" >> $GITHUB_PATH

      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
            ruby-version: 2.7
            bundler-cache: true

      - name: Install puppet-lint
        run: gem install puppet-lint

      - name: Run puppet-lint
        run: puppet-lint . --sarif > puppet-lint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: puppet-lint-results.sarif
          wait-for-processing: true
